name: Go Release

on:
  push:
    tags:
      - 'v*.*.*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'The version tag to build (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        goarch: [amd64, arm64]
        exclude:
          - os: windows-latest
            goarch: arm64 # Windows on ARM is currently not widely used for this type of application, so we can exclude it to save build time.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'

      - name: Build
        env:
          GOOS: ${{ (matrix.os == 'ubuntu-latest' && 'linux') || (matrix.os == 'windows-latest' && 'windows') }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Define the output filename based on OS and architecture
          BINARY_NAME="ndiff-go-${{ env.GOOS }}-${{ env.GOARCH }}"
          if [ "$GOOS" == "windows" ]; then
            BINARY_NAME+=".exe"
          fi
          
          # Use the version from the workflow input for manual runs, or the git ref for pushes
          VERSION=${{ github.event.inputs.version_tag || github.ref_name }}
          
          go build -o $BINARY_NAME -ldflags "-X 'main.version=$VERSION'"

          # Move the binary to the root directory for easy access
          # mv $BINARY_NAME .

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version_tag || github.ref_name }}
          files: ndiff-go*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
